import * as constants from './constants';
import {fromJS} from 'immutable';
const defaultState =fromJS({
    "user_id": 0,
    "user_name": "string",
    "user_num": "string",
    add_Ta: [ 1, 2,3,4, 5, 6,7,8, 9,10,1, 2,3,4, 5, 6,7,8, 9,10],
    "add_Tp": [ 1, 2,3,4, 5, 6,7,8, 9,10,1, 2,3,4, 5, 6,7,8, 9,10],
    uu_id:"",
    "Tp_1": 70,
    "Tp_2": 68.2,
    "Tp_3": 66.6,
    "Tp_4": 65.2,
    "Tp_5": 63.8,
    "Tp_6": 62.6,
    "Tp_7": 61.4,
    "Tp_8": 60.2,
    "Tp_9": 59.1,
    "Tp_10": 58.1,
    "Tp_11": 56.8,
    "Tp_12": 56.0,
    "Tp_13": 55.1,
    "Tp_14": 54.2,
    "Tp_15": 53.4,
    "Tp_16": 52.5,
    "Tp_17": 51.7,
    "Tp_18": 51,
    "Tp_19": 50.3,
    "Tp_20": 49.5,
    "hb_1": 7.35,
    "hb_2": 7.35,
    "hb_3": 7.35,
    "hb_4": 7.35,
    "hb_5": 7.35,
    "hb_6": 7.35,
    "Ta": 60.1,
    "Tp": 51.8,
    "hp": 7.7,
    "D1": 1,
    "D2": 1,
    "D3": 1,
    "D4": 1,
    "D5": 1,
    "D6": 1,
    "m": 863.6,
    "c": 0.385,
    "space1": 20,
    "space2": 20,
    "p1": "string",
    "p2": "string",
    "t": 0,
    "img1": "string",
    "img2": "string",
    "img10": "string",
    "img20": "string",
    "k": 0
});

export default (state=defaultState,action)=> {
    const data = action.data;
    switch (action.type) {
        case constants.CHANGE_DATAS:
            return state.merge({
                user_id:data.get('user_id'),
                user_name:data.get('user_name'),
                user_num:data.get('user_num'),
                add_Ta:data.get('add_Ta'),
                add_Tp:data.get('add_Tp'),
                uu_id:data.get('uu_id'),
                Tp_1:data.get('Tp_1'),
                Tp_2:data.get('Tp_2'),
                Tp_3:data.get('Tp_3'),
                Tp_4:data.get('Tp_4'),
                Tp_5:data.get('Tp_5'),
                Tp_6:data.get('Tp_6'),
                Tp_7:data.get('Tp_7'),
                Tp_8:data.get('Tp_8'),
                Tp_9:data.get('Tp_9'),
                Tp_10:data.get('Tp_10'),
                Tp_11:data.get('Tp_11'),
                Tp_12:data.get('Tp_12'),
                Tp_13:data.get('Tp_13'),
                Tp_14:data.get('Tp_14'),
                Tp_15:data.get('Tp_15'),
                Tp_16:data.get('Tp_16'),
                Tp_17:data.get('Tp_17'),
                Tp_18:data.get('Tp_18'),
                Tp_19:data.get('Tp_19'),
                Tp_20:data.get('Tp_20'),
                hb_1:data.get('hb_1'),
                hb_2:data.get('hb_2'),
                hb_3:data.get('hb_3'),
                hb_4:data.get('hb_4'),
                hb_5:data.get('hb_5'),
                hb_6:data.get('hb_6'),
                Ta:data.get('Ta'),
                Tp:data.get('Tp'),
                hp:data.get('hp'),
                D1:data.get('D1'),
                D2:data.get('D2'),
                D3:data.get('D3'),
                D4:data.get('D4'),
                D5:data.get('D5'),
                D6:data.get('D6'),
                m:data.get('m'),
                c:data.get('c'),
                space1:data.get('space1'),
                space2:data.get('space2'),
                p1:data.get('p1'),
                p2:data.get('p2'),
                t:data.get('t'),
                img1:data.get('img1'),
                img2:data.get('img2'),
                img10:data.get('img10'),
                img20:data.get('img20'),
                k:data.get('k')
            });
            //改变每个input的store数据
        case constants.CHANGE_INPUT_VALUE:
            return state.set(action.name,action.value);
        case constants.CHANGE_DATAS_FOREVER_ARRAYS:
            return state.setIn([action.nameArr,action.index],action.value);
        default:
            return state;
    }
}